name: nezha-agent

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Extract version from Dockerfile
        id: extract_version
        run: |
          NEZHA_VER=$(grep -oP '(?<=ARG NEZHA_VER=)\d+\.\d+\.\d+' Dockerfile)
          echo "NEZHA_VER=${NEZHA_VER}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
          tags: tchivs/nezha-agent:${{ env.NEZHA_VER }}
