name: Docker Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 手动触发

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          NEZHA_VER=$(grep -oP '(?<=ARG NEZHA_VER=)\d+\.\d+\.\d+' Dockerfile)
          echo "NEZHA_VER=${NEZHA_VER}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
          tags: |
            tchivs/nezha-agent:${{ env.NEZHA_VER }}
            tchivs/nezha-agent:latest